"""empty message

Revision ID: 13e932d53f47
Revises: 51c91c1b0192
Create Date: 2015-11-21 11:47:31.040456

"""

# revision identifiers, used by Alembic.
revision = '13e932d53f47'
down_revision = '51c91c1b0192'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
