"""empty message

Revision ID: 1741a1c296b6
Revises: 13e932d53f47
Create Date: 2015-11-22 13:35:51.457353

"""

# revision identifiers, used by Alembic.
revision = '1741a1c296b6'
down_revision = '13e932d53f47'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('image_url', sa.String(length=256)),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url'),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmarks')
    ### end Alembic commands ###
